id: A6C8C96B6
title: 'Great Pangs of Devotion: A Prayer to the Gurus and Three Roots in General
  and Especially the Two Thartsé Khenchen Vajradhara Brothers and Jamyang Khyentse
  Wangpo'
type: translation
pechas:
- IC29B3024
- I3BF6C35C
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2023-01-04 12:02:26.289738
  last_modified_at: 2023-01-04 12:02:26.289760
  collections:
  - Jampa Kunga Tendzin Series
  - Works of Tibetan Masters
alignment_to_base:
  IC29B3024/A0BF: '9768'
  I3BF6C35C/DE9D: '9768'
